// STUFF ADDED IN THE CHURCH EQUIPMENT PORT

/datum/design/autolathe/sword/nt_sword/name = "Mekhane Shortsword"
/datum/design/autolathe/sword/nt_longsword/name = "Mekhane Longsword"
/datum/design/autolathe/sword/nt_dagger/name = "Mekhane Dagger"
/datum/design/autolathe/sword/nt_halberd/name = "Mekhane Halberd"
/datum/design/autolathe/sword/nt_scourge/name = "Mekhane Scourge"
/datum/design/autolathe/shield/nt_shield/name = "Mekhane Shield"
/datum/design/autolathe/grenade/nt_explosive/name = "MEK OBG \"Nova\""
/datum/design/autolathe/grenade/nt_flashbang/name = "MEK FBG \"Pulsar\""
/datum/design/autolathe/grenade/nt_frag/name = "MEK DFG \"Flare\""
/datum/design/autolathe/grenade/nt_smokebomb/name = "MEK SG \"Nebula\""
/obj/item/weapon/tool/sword/nt/name = "Mekhane Shortsword"
/obj/item/weapon/tool/sword/nt/longsword/name = "Mekhane Longsword"
/obj/item/weapon/tool/knife/dagger/nt/name = "Mekhane Dagger"
/obj/item/weapon/tool/sword/nt/halberd/name = "Mekhane Halberd"
/obj/item/weapon/tool/sword/nt/scourge/name = "Mekhane Scourge"
/obj/item/weapon/shield/riot/nt/name = "Mekhane Shield"
/obj/item/weapon/grenade/explosive/nt/name = "MEK OBG \"Nova\""
/obj/item/weapon/grenade/flashbang/nt/name = "MEK FBG \"Pulsar\""
/obj/item/weapon/grenade/smokebomb/nt/name = "MEK SG \"Nebula\""
/obj/item/weapon/grenade/frag/nt/name = "MEK DFG \"Flare\""

// CLOTHING
/datum/design/bioprinter/nt_clothes/acolyte_armor/name = "MEK Acolyte Armor"
/datum/design/bioprinter/nt_clothes/agrolyte_armor/name = "MEK Agrolyte Armor"
/datum/design/bioprinter/nt_clothes/custodian_armor/name = "MEK Custodian Armor"
/datum/design/bioprinter/nt_clothes/preacher_coat/name = "MEK Preacher Longcoat"
/datum/design/bioprinter/nt_clothes/acolyte_jacket/name = "MEK Acolyte Jacket"
/datum/design/bioprinter/nt_clothes/sports_jacket/name = "MEK Sports Jacket"
/datum/design/bioprinter/nt_clothes/acolyte_uniform/name = "MEK Acolyte Garment"
/datum/design/bioprinter/nt_clothes/sports_uniform/name = "MEK Sport Clothes"
/datum/design/bioprinter/nt_clothes/church_uniform/name = "MEK Church Garment"

/datum/design/bioprinter/belt/utility/neotheology/name = "Mekhanite utility belt"
/datum/design/bioprinter/belt/security/neotheology/name = "Mekhanite tactical belt"
