/obj/structure/closet/secure_closet/personal/miner/populate_contents()
	new /obj/item/weapon/storage/backpack/industrial(src)
	new /obj/item/weapon/storage/backpack/satchel/industrial(src)
	new /obj/item/device/radio/headset/headset_cargo(src)
	new /obj/item/clothing/under/rank/miner(src)
	new /obj/item/clothing/gloves/thick(src)
	new /obj/item/clothing/glasses/powered/meson(src)
	new /obj/item/clothing/shoes/color/black(src)
	new /obj/item/device/scanner/gas(src)
	new /obj/item/device/lighting/toggleable/flashlight/heavy(src)
	new /obj/item/device/t_scanner(src)
